### ISSUE TITLE
ConvBERT, Electra

### ISSUE THREAD

**Issue by lumpidu** [ankane/transformers-ruby#8]
Hi,

I'd love to see support for Electra or ConvBERT models. Here are 2 concrete examples:

- [ ] https://huggingface.co/Icelandic-lt/convbert-base-igc-is
- [ ] https://huggingface.co/Icelandic-lt/electra-base-igc-is

**Comment by ankane** [comment]
Hi @lumpidu, porting models is fairly tedious, so if you just need inference, I'd recommend exporting the models to ONNX with [Optimum](https://github.com/huggingface/optimum) and using [Informers](https://github.com/ankane/informers) (you'll also need to save the fast tokenizer as `tokenizer.json` since it isn't present in the repo).

**Comment by lumpidu** [comment]
Ah I didn't know that there is a generic alternative via ONNX and informers. Wouldn't this be worth mentioning inside the Readmes ? And thanks btw. for your contributions for Ruby and ML !

**Comment by ankane** [comment]
It's linked in the intro.

Also, there's a [conversion script](https://github.com/huggingface/transformers.js?tab=readme-ov-file#convert-your-models-to-onnx) in Transformers.js that may be easier than using Optimum directly.
